# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master, add-ci ]
    paths-ignore:
    - '*.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
    - '*.md'

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Restore node_modules
      uses: actions/cache@v2
      id: node_modules-cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node${{ matrix.node-version}}-${{ hashFiles('**/yarn.lock') }}

    - name: Install dependencies
      if: steps.node_modules-cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile

    - name: Test
      run: yarn test
